### ISSUE TITLE
Rückgabewert des Calculators

### ISSUE THREAD

**Issue by pmehnert** [g4rgoil/graphing_calculator#19]
@dermondbaer  
Der aktuelle Stand der Dinge ist, dass du im GUI eine Variable Calculator definierst. Wenn du dann einen Ausdruck berechen willst, rufst du die Methode calculate_expression() des Calculators auf. Innerhalb dieser Methode wird der Ausdruck geparst und daraufhin berechnet.
Ist in dem Ausdruck eine Variable vorhanden, wird der Ausdruck, bzw sein ParserTree so weit wie möglich vereinfacht.
Dementsprechend hätte die calculate_expression() Methode einen ParserTree als return type, auch wenn keine Variable in dem Ausdruck vorhanden war. Was hälst du davon?

PS. Der Calculator ist im master branch noch nicht implementiert

**Comment by dermondbaer** [comment]
Ist für mich in Ordnung, wenn das so herum verschachtelt ist ... falls es funktioniert ^^. Momentan ist es übrigens so, dass der Parser einige syntaktische Fehler noch klaglos hinnimmt, darunter mehrere hintereinander folgende Rechenzeichen etc. Ich denke, das kommt daher, dass er in Postfix umwandelt und vermutlich auch Postfix akzeptiert, genauer nachgeschaut hab ich aber nicht. Man könnte das natürlich als intentional betrachten, aber ich denke, es ist besser, da strikt zu bleiben und auf einer korrekte mathematischen Schreibweise zu bestehen.
Was ich außerdem noch als Anregung hätte, quasi ein Feature-Request, wäre eine genauere Angabe der beim Parsen entstandenen Fehler. Ich weiß, dass das schwierig sein könnte, aber eine Positionsangabe im String oder im ParserTree wäre hilfreich. Ich weiß nicht, inwiefern man mit dem Errorsystem in Python mehr Informationen als nur den Typ eines Errors übertragen bzw. weitergeben kann, wenn das zu beschränkt ist, könnten wir ja einen normalen Rückgabewert benutzen, z.B. ein Tuple der Form ( >Error ja/nein<, >Ergebnis<, >Position des Errors<, >Typ des Errors<). Müssten wir noch mal überlegen. Schau vielleicht mal, ob das machbar ist und wie viel Aufwand es bedeuten würde.

**Comment by pmehnert** [comment]
Ich implementiere jetzt erstmal den Caclulator. Viele bisher akzeptierte Fehler werden dann nen Error erzeugen. Über alles weiter mach ich mir später Gedanken.
Lass den Thread einfach offen, dann denk ich dran.

**Comment by dermondbaer** [comment]
Oke.

**Comment by pmehnert** [comment]
Ich weiß nicht ob du es schon gesehn hast, der Calculator bzw. eine erste Version davon ist jetzt im Master.
Der hat vermutlich noch 100 Bugs aber naja.

**Comment by pmehnert** [comment]
Kann ich den Thread hier mal schließen?
